import Head from "next/head";
import Image from "next/image";
import MainLayout from "../components/Layouts/MainLayout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Park N Parcel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <div className="w-full bg-primary py-12">
          <div className="container mx-auto px-4">
            <div className="text-center">
              <p className="mb-1 text-3xl text-white font-extrabold drop-shadow-lg">New</p>
              <h1 className="mb-2 text-5xl text-white font-semibold drop-shadow-lg">
                Local Delivery to Your Letterbox
              </h1>
              <p className="text-white">Postage-paid packaging, made using recycled materials</p>
            </div>
          </div>
        </div>

        <div className="container py-10 mx-auto">
          <div className="max-w-screen-md mx-auto mb-14">
            <div className="grid grid-cols-2 gap-6">
              <Image
                src="/images/pnp-pack-front.jpg"
                width="500"
                height="500"
                alt="Pack"
                className="w-full h-auto"
              />
              <Image
                src="/images/pnp-pack-back.jpg"
                width="500"
                height="500"
                alt="Pack"
                className="w-full h-auto"
              />
            </div>
          </div>
          <div className="text-center mb-14">
            <h2 className="text-4xl text-primary font-semibold">Why Choose PNP Packs?</h2>
          </div>
          <div className="max-w-screen-lg mx-auto">
            <div className="grid grid-cols-3 gap-x-6 gap-y-12">
              <div className="flex space-x-6">
                <Image
                  src="/images/icon-tick.png"
                  width="32"
                  height="32"
                  alt="Icon"
                  className="w-8 h-8"
                />
                <p className="pt-1 text-lg text-primary font-medium">24/7 Real-time Tracking</p>
              </div>
              <div className="flex space-x-6">
                <Image
                  src="/images/icon-tick.png"
                  width="32"
                  height="32"
                  alt="Icon"
                  className="w-8 h-8"
                />
                <p className="pt-1 text-lg text-primary font-medium">Recycled Materials</p>
              </div>
              <div className="flex space-x-6">
                <Image
                  src="/images/icon-tick.png"
                  width="32"
                  height="32"
                  alt="Icon"
                  className="w-8 h-8"
                />
                <p className="pt-1 text-lg text-primary font-medium">Letterbox Delivery</p>
              </div>
              <div className="flex space-x-6">
                <Image
                  src="/images/icon-tick.png"
                  width="32"
                  height="32"
                  alt="Icon"
                  className="w-8 h-8"
                />
                <p className="pt-1 text-lg text-primary font-medium">No Weight Limit</p>
              </div>
              <div className="flex space-x-6">
                <Image
                  src="/images/icon-tick.png"
                  width="32"
                  height="32"
                  alt="Icon"
                  className="w-8 h-8"
                />
                <p className="pt-1 text-lg text-primary font-medium">Local Delivery</p>
              </div>
              <div className="flex space-x-6">
                <Image
                  src="/images/icon-tick.png"
                  width="32"
                  height="32"
                  alt="Icon"
                  className="w-8 h-8"
                />
                <p className="pt-1 text-lg text-primary font-medium">
                  Deliver within 3 working days
                </p>
              </div>
            </div>
          </div>
        </div>

        <div className="bg-primary py-16">
          <div className="container mx-auto">
            <div className="w-full px-20 py-10 bg-white rounded-[50px]">
              <div className="text-center mb-8">
                <h2 className="text-4xl text-primary font-semibold mb-4">
                  Available Types &amp; Sizes
                </h2>
                <p className="text-xl text-secondary font-semibold">From $32.00</p>
              </div>
              <div className="grid grid-cols-4 gap-11">
                <div>
                  <div className="flex items-end w-full h-40 mb-5">
                    <Image
                      src="/images/pnp-pack-small.png"
                      width="500"
                      height="500"
                      alt="Item"
                      className="w-full h-32 object-contain"
                    />
                  </div>
                  <div className="px-6">
                    <p className="font-bold text-primary">Small PNP Packs</p>
                    <p className="text-primary">Pack of 10</p>
                    <div className="text-center py-4">
                      <p className="text-2xl text-secondary font-bold">$00</p>
                    </div>
                    <p className="font-bold text-primary">Dimensions:</p>
                    <p className="text-primary">220mmx150mm</p>
                  </div>
                </div>
                <div>
                  <div className="flex items-end w-full h-40 mb-5">
                    <Image
                      src="/images/pnp-pack-medium.png"
                      width="500"
                      height="500"
                      alt="Item"
                      className="w-full h-auto object-contain"
                    />
                  </div>
                  <div className="px-6">
                    <p className="font-bold text-primary">Medium PNP Packs</p>
                    <p className="text-primary">Pack of 10</p>
                    <div className="text-center py-4">
                      <p className="text-2xl text-secondary font-bold">$00</p>
                    </div>
                    <p className="font-bold text-primary">Dimensions:</p>
                    <p className="text-primary">320mmx220mm</p>
                  </div>
                </div>
                <div>
                  <div className="flex items-end w-full h-40 mb-5">
                    <Image
                      src="/images/pnp-pack-small-padded.png"
                      width="500"
                      height="500"
                      alt="Item"
                      className="w-full h-32 object-contain"
                    />
                  </div>
                  <div className="px-6">
                    <p className="font-bold text-primary">Small PNP Packs Padded</p>
                    <p className="text-primary">Pack of 10</p>
                    <div className="text-center py-4">
                      <p className="text-2xl text-secondary font-bold">$00</p>
                    </div>
                    <p className="font-bold text-primary">Dimensions:</p>
                    <p className="text-primary">220mmx150mm</p>
                  </div>
                </div>
                <div>
                  <div className="flex items-end w-full h-40 mb-5">
                    <Image
                      src="/images/pnp-pack-medium-padded.png"
                      width="500"
                      height="500"
                      alt="Item"
                      className="w-full h-auto object-contain"
                    />
                  </div>
                  <div className="px-6">
                    <p className="font-bold text-primary">Medium PNP Packs Padded</p>
                    <p className="text-primary">Pack of 10</p>
                    <div className="text-center py-4">
                      <p className="text-2xl text-secondary font-bold">$00</p>
                    </div>
                    <p className="font-bold text-primary">Dimensions:</p>
                    <p className="text-primary">320mmx220mm</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="container py-16 mx-auto">
          <div className="w-full px-20 py-12 bg-primary rounded-[100px]">
            <div className="text-center mb-8">
              <h2 className="text-4xl text-white font-semibold mb-4">
                Create &amp; Send Delivery Orders
              </h2>
              <p className="text-xl font-light text-white">Step-by-Step Create Order Guide</p>
            </div>
            <div className="grid grid-cols-4 gap-8">
              <div>
                <Image
                  src="/images/step-1.png"
                  width="500"
                  height="500"
                  alt="Step"
                  className="w-full h-40 object-contain object-center mb-4"
                />
                <div className="text-center mb-4">
                  <p className="text-white font-bold">Purchase</p>
                </div>
                <p className="text-white font-light">
                  Order your PNP packs online at _ or offline in the following list of Parker
                  Points.
                </p>
              </div>
              <div>
                <Image
                  src="/images/step-2.png"
                  width="500"
                  height="500"
                  alt="Step"
                  className="w-full h-40 object-contain object-center mb-4"
                />
                <div className="text-center mb-4">
                  <p className="text-white font-bold">Purchase</p>
                </div>
                <p className="text-white font-light">
                  Send Create home pick-up (For orders above 5 parcels) or drop it off at any Parker
                  Point
                </p>
              </div>
              <div>
                <Image
                  src="/images/step-3.png"
                  width="500"
                  height="500"
                  alt="Step"
                  className="w-full h-40 object-contain object-center mb-4"
                />
                <div className="text-center mb-4">
                  <p className="text-white font-bold">Purchase</p>
                </div>
                <p className="text-white font-light">
                  Track Check the status of your parcels in real time at{" "}
                  <a href="#" className="underline">
                    track.parknparcel.com
                  </a>
                </p>
              </div>
              <div>
                <Image
                  src="/images/step-4.png"
                  width="500"
                  height="500"
                  alt="Step"
                  className="w-full h-40 object-contain object-center mb-4"
                />
                <div className="text-center mb-4">
                  <p className="text-white font-bold">Purchase</p>
                </div>
                <p className="text-white font-light">
                  Receive To be delivered with 3 working days to your recipient’s letterbox.
                </p>
              </div>
            </div>
          </div>
        </div>

        <div className="max-w-screen-md mx-auto py-10">
          <div className="text-center mb-8">
            <h2 className="text-4xl text-primary font-semibold">Take Note</h2>
          </div>
          <ul className="list list-disc">
            <li className="text-primary font-light">
              You do not have to write any information on your PNP Pack. We will use the
              pre-generated Tracking ID and information provided in the order creation process to
              deliver your parcel.
            </li>
            <li className="text-primary font-light">
              PNP Packs will be rejected if the order has not been created in your Park N Parcel
              dashboard.
            </li>
            <li className="text-primary font-light">
              PNP will not be proceed with any delivery should your PNP packs be attached to any
              other parcels.
            </li>
            <li className="text-primary font-light">Prices are inclusive of prevailing GST.</li>
          </ul>
        </div>

        <div className="bg-primary py-16">
          <div className="max-w-screen-lg mx-auto">
            <div className="text-center mb-12">
              <h2 className="text-4xl text-white font-semibold">Happy Customers</h2>
            </div>

            <Image
              src="/images/testimonials.jpg"
              width="1000"
              height="400"
              alt="Testimonials"
              className="w-full h-auto"
            />
          </div>
        </div>

        <div className="max-w-screen-md mx-auto py-24">
          <ul className="list list-disc">
            <li className="text-primary font-light">
              You do not have to write any information on your PNP Pack. We will use the
              pre-generated Tracking ID and information provided in the order creation process to
              deliver your parcel.
            </li>
          </ul>
        </div>

        <div className="bg-primary py-16">
          <div className="container mx-auto">
            <div className="grid grid-cols-3 gap-10">
              <div>
                <p className="text-xl text-white font-bold mb-6">Park N Parcel</p>
                <ul>
                  <li>
                    <a href="#" className="text-white">
                      Track your parcel
                    </a>
                  </li>
                </ul>
              </div>
              <div>
                <p className="text-xl text-white font-bold mb-6">Guides</p>
                <ul>
                  <li>
                    <a href="#" className="text-white">
                      PNP Packs Order Creation Guide
                    </a>
                  </li>
                </ul>
              </div>
              <div>
                <p className="text-xl text-white font-bold mb-6">Support</p>
              </div>
            </div>
          </div>
        </div>
      </MainLayout>
    </>
  );
}
